import { useCallback, useState } from 'react';
import {
  Button,
  InputSelect,
  DropdownSection,
  DropdownOption,
} from '@ama-pt/agora-design-system';
// 👇 GENERATED by orval from api/openapi.json — accepts the server-side filter params.
import { useListEstablishments, useListEstablishmentNames } from '../../api/generated/api';
import { DemoTable } from '../../components/DemoTable/DemoTable';

/**
 * Filter page: a filter form + a server-driven results table.
 *
 * ⛔ ALL filtering happens on the backend. The filter values are sent as query
 * params to the generated hook; the server narrows the data. We NEVER call
 * .filter()/.sort()/.slice() on the response. (agora-ui-standards §8, react-patterns §3)
 */
type Estado = 'Ativo' | 'Suspenso' | 'Encerrado';
type Periodo = '2026-Q1' | '2026-Q2' | '2026-Q3' | '2026-Q4';
const PERIODOS: Periodo[] = ['2026-Q1', '2026-Q2', '2026-Q3', '2026-Q4'];

export function EstablishmentsPage() {
  // Draft filter inputs — all three are MULTI-select, so they hold arrays.
  const [nomes, setNomes] = useState<string[]>([]);
  const [estados, setEstados] = useState<Estado[]>([]);
  const [periodos, setPeriodos] = useState<Periodo[]>([]);

  // Applied filters — only these reach the query, and only on "Pesquisar".
  const [applied, setApplied] = useState<{ nome?: string[]; estado?: Estado[]; periodo?: Periodo[] }>({});
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  // All three filters apply together (server ANDs them): nome ∈ AND estado ∈ AND periodo ∈.
  const { data, isLoading } = useListEstablishments({
    nome: applied.nome?.length ? applied.nome : undefined,
    estado: applied.estado?.length ? applied.estado : undefined,
    periodo: applied.periodo?.length ? applied.periodo : undefined,
    page,
    pageSize,
  });
  const rows = data?.items ?? [];
  const total = data?.total ?? 0;

  // Nome dropdown options come from their own API call (swagger /establishments/names).
  const { data: nameOptions = [] } = useListEstablishmentNames();

  const handleSearch = useCallback(() => {
    setApplied({ nome: nomes, estado: estados, periodo: periodos });
    setPage(1); // filters changed → back to first page
  }, [nomes, estados, periodos]);

  const handleClear = useCallback(() => {
    setNomes([]);
    setEstados([]);
    setPeriodos([]);
    setApplied({});
    setPage(1);
  }, []);

  return (
    <main className="page">
      <h1 className="demo-page-title">Estabelecimentos</h1>

      <div className="bg-white" style={{ border: '1px solid var(--color-neutral-100)' }}>
        {/* Section 1 — Filters. <form> so Enter triggers the search. */}
        <form className="p-32" onSubmit={(e) => { e.preventDefault(); handleSearch(); }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '32px', alignItems: 'start' }}>
              <InputSelect
                label="Nome"
                placeholder="Todos"
                type="checkbox"
                hideSectionNames
                allSelectedLabel="Todos os nomes"
                pluralSelectedPlaceholder="{n} nomes selecionados"
                searchable
                searchInputPlaceholder="Procurar nome…"
                searchInputAriaLabel="Procurar nome"
                onChange={(opts) => setNomes(opts.map((o) => o.value))}
              >
                <DropdownSection name="nome">
                  {nameOptions.map((n) => (
                    <DropdownOption key={n} value={n} selected={nomes.includes(n)}>{n}</DropdownOption>
                  ))}
                </DropdownSection>
              </InputSelect>
              <InputSelect
                label="Estado"
                placeholder="Todos"
                type="checkbox"
                hideSectionNames
                allSelectedLabel="Todos os estados"
                pluralSelectedPlaceholder="{n} estados selecionados"
                onChange={(opts) => setEstados(opts.map((o) => o.value as Estado))}
              >
                <DropdownSection name="estado">
                  <DropdownOption value="Ativo" selected={estados.includes('Ativo')}>Ativo</DropdownOption>
                  <DropdownOption value="Suspenso" selected={estados.includes('Suspenso')}>Suspenso</DropdownOption>
                  <DropdownOption value="Encerrado" selected={estados.includes('Encerrado')}>Encerrado</DropdownOption>
                </DropdownSection>
              </InputSelect>
              <InputSelect
                label="Período"
                placeholder="Todos"
                type="checkbox"
                hideSectionNames
                allSelectedLabel="Todos os períodos"
                pluralSelectedPlaceholder="{n} períodos selecionados"
                onChange={(opts) => setPeriodos(opts.map((o) => o.value as Periodo))}
              >
                <DropdownSection name="periodo">
                  {PERIODOS.map((p) => (
                    <DropdownOption key={p} value={p} selected={periodos.includes(p)}>{p}</DropdownOption>
                  ))}
                </DropdownSection>
              </InputSelect>
            </div>

            {/* Button row — always last, flex-end, 32px gap. */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '32px' }}>
              <Button
                type="button"
                variant="primary"
                appearance="outline"
                className="demo-btn-secondary"
                onClick={handleClear}
                disabled={isLoading}
              >
                Limpar
              </Button>
              <Button
                type="submit"
                variant="primary"
                appearance="solid"
                className="demo-btn-primary"
                disabled={isLoading}
              >
                {isLoading ? 'A pesquisar…' : 'Pesquisar'}
              </Button>
            </div>
          </div>
        </form>

        {/* Divider between filters and results. */}
        <div style={{ height: '1px', background: 'var(--color-neutral-500)', margin: '0 32px' }} />

        {/* Section 2 — server-driven results table. */}
        <div className="p-32">
          <DemoTable
            aria-label="Estabelecimentos"
            pagination={{
              total,
              page,
              pageSize,
              onPageChange: setPage,
              onPageSizeChange: (size) => { setPageSize(size); setPage(1); },
            }}
          >
            <DemoTable.Header>
              <DemoTable.Column width="220px">Estabelecimento</DemoTable.Column>
              <DemoTable.Column width="160px">Estado</DemoTable.Column>
              <DemoTable.Column>Período</DemoTable.Column>
              <DemoTable.Column width="120px" align="center">Ações</DemoTable.Column>
            </DemoTable.Header>

            <DemoTable.Body
              loading={isLoading}
              empty={!isLoading && rows.length === 0}
              emptyLabel="Nenhum resultado encontrado."
            >
              {rows.map((row) => (
                <DemoTable.Row key={row.id} onClick={() => console.log('detalhes', row.id)}>
                  <DemoTable.Cell>{row.nome}</DemoTable.Cell>
                  <DemoTable.Cell>{row.estado}</DemoTable.Cell>
                  <DemoTable.Cell>{row.periodo}</DemoTable.Cell>
                  <DemoTable.Cell fill align="center">
                    <button type="button" className="demo-btn demo-btn-link">Detalhes</button>
                  </DemoTable.Cell>
                </DemoTable.Row>
              ))}
            </DemoTable.Body>
          </DemoTable>
        </div>
      </div>
    </main>
  );
}
